// Local-only diagnostic controls. Uses production world/renderer and movement.
ensureGameLogin=async()=>{};initializeCloud=async()=>{};save=queueCloudSave=()=>{};cloudReady=false;syncOnlineWorld=()=>{};frame=()=>{};
s=defaults();s.character={name:'Motion review',look:0,frame:'male',hair:0};s.tutorial=tutorialSteps.length;s.tutorialReward=true;s.storyOpeningSeen=true;s.metRowan=true;s.sceneId='overworld';s.x=55;s.y=61;
worldCycleSeconds=()=>180;
let motionRun=false,motionSamples=[],motionStep=0;
const motionPhases=['standing','walking','running','orbit','reverse','enter-exit','zoom-range','maximum-zoom'];
function motionPeers(){onlineScene=currentScene;for(let i=0;i<6;i++){const x=53+i%3*2,y=63+Math.floor(i/3)*2;onlinePeers.set('qa'+i,{id:'qa'+i,name:'Test player '+(i+1),username:'qa'+i,seen:Date.now(),x,y,drawX:x,drawY:y,look:i%4,frame:i%2?'female':'male',hair:0,equipment:{},phase:0,heading:0,drawHeading:0,lastVisualAt:performance.now(),samples:[]});}}
function motionReset(){motionRun=false;activateScene('overworld',55,61);view3d.zoom=14;view3d.yaw=-.55;view3d.tilt=.85;time=10;path=[];target=null;motionPeers();if(typeof syncCameraZoom==='function')syncCameraZoom();renderUI();}
function motionInfo(){const gl=realmGPU?.gl,ext=gl?.getExtension('WEBGL_debug_renderer_info');return {viewport:screen,buffer:realmGPU?[realmGPU.surface.width,realmGPU.surface.height]:null,scale:realmResolution.scale,pixelRatio:devicePixelRatio,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unavailable',aa:gl?.getContextAttributes()?.antialias,objects:objects.length,buildings:buildings.length,peers:onlinePeers.size,heap:performance.memory?.usedJSHeapSize};}
function motionDraw(){draw();document.getElementById('motionInfo').textContent=JSON.stringify(motionInfo());}
function motionStatistics(){const list=motionSamples.map(s=>s.frameMs).sort((a,b)=>a-b),sum=list.reduce((a,b)=>a+b,0),tail=list.slice(Math.floor(list.length*.99));return {frames:list.length,averageFPS:1000*list.length/sum,onePercentLowFPS:1000/(tail.reduce((a,b)=>a+b,0)/tail.length),meanFrameMs:sum/list.length,p99FrameMs:list[Math.floor(list.length*.99)],spikesOver33ms:list.filter(v=>v>33).length,maxFrameMs:list.at(-1),scaleRange:[Math.min(...motionSamples.map(s=>s.scale)),Math.max(...motionSamples.map(s=>s.scale))],scene:motionInfo(),samples:motionSamples};}
function motionStart(){motionReset();motionRun=true;motionStep=0;motionSamples=[];let previous=null,phaseStarted=null,phaseIndex=0,frameInPhase=0;const phaseDuration=7500;
 const tick=now=>{if(!motionRun)return;phaseStarted??=now;const progress=(now-phaseStarted)/phaseDuration,phase=motionPhases[phaseIndex],dt=previous===null?1/60:Math.min((now-previous)/1000,.05);if(previous!==null)observeRenderTime(now-previous);const start=performance.now();time+=dt;
  if(phase==='walking'||phase==='running'){s.running=phase==='running';if(!path.length)walkTo(Math.floor(progress*4)%2?55:60,61);advanceMovement(dt);}
  if(phase==='orbit')view3d.yaw+=.045;
  if(phase==='reverse')view3d.yaw+=(frameInPhase%4<2?1:-1)*.065;
  if(phase==='enter-exit'){const b=buildings.find(b=>b.walkIn&&b.service?.destination==='willowInn');if(b&&frameInPhase===0){activateScene('overworld',b.service.x,b.service.y+2);setWalkInDoor(b.service,true,true);walkTo(...doorApproach(b.service,true));}if(b&&progress>.5&&withinWalkIn(b,px,py))walkTo(...doorApproach(b.service,false));advanceMovement(dt);updateDoorThreshold();}
  if(phase==='zoom-range'){view3d.zoom=14+51*Math.sin(Math.min(1,progress)*Math.PI);if(typeof syncCameraZoom==='function')syncCameraZoom();}
  if(phase==='maximum-zoom'){view3d.zoom=14;view3d.yaw+=.045;}
  livingWorld(dt);advanceWorldActors(dt);for(const p of onlinePeers.values())p.seen=Date.now();draw();const cpuMs=performance.now()-start;
  if(previous!==null)motionSamples.push({phase,frameMs:now-previous,cpuMs,scale:realmResolution.scale,zoom:view3d.zoom});previous=now;frameInPhase++;document.getElementById('motionInfo').textContent=phase+' · '+motionSamples.length+' frames · '+Math.round(realmResolution.scale*100)+'%';
  if(progress>=1){phaseIndex++;frameInPhase=0;phaseStarted=null;}if(phaseIndex===motionPhases.length){motionRun=false;document.getElementById('motionResults').textContent=JSON.stringify(motionStatistics());document.getElementById('motionInfo').textContent='Replay complete';return;}requestAnimationFrame(tick);
 };requestAnimationFrame(tick);
}
boot().then(()=>{const panel=document.createElement('section');panel.style='position:fixed;top:4px;left:115px;right:170px;z-index:100;background:#101c28e8;color:white;padding:6px;font:12px Arial';panel.innerHTML='<button id="motionStart">Run motion stress test</button><button id="motionFrame">Reset view</button><button id="motionNudge">Move one subpixel</button><button id="motionStop">Stop replay</button><span id="motionInfo">Preparing</span><details><summary>Recorded measurements</summary><pre id="motionResults" style="max-height:220px;overflow:auto"></pre></details>';document.body.append(panel);document.getElementById('motionStart').onclick=motionStart;document.getElementById('motionStop').onclick=()=>{motionRun=false;document.getElementById('motionResults').textContent=JSON.stringify(motionStatistics());};document.getElementById('motionFrame').onclick=()=>{motionReset();requestAnimationFrame(motionDraw);};document.getElementById('motionNudge').onclick=()=>{px+=.01;py+=.01;requestAnimationFrame(motionDraw);};document.getElementById('cameraZoom')?.addEventListener('input',()=>requestAnimationFrame(motionDraw));motionReset();requestAnimationFrame(motionDraw);});
