const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const noop=()=>{},els={},storage={};
function el(){return {textContent:'',innerHTML:'',style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},appendChild:noop,querySelectorAll:()=>[],addEventListener:noop,setAttribute:noop,getContext:()=>new Proxy({},{get:()=>noop}),showModal(){this.open=true},close(){this.open=false},getBoundingClientRect:()=>({width:800,height:390,left:0,top:0})};}
assert.match(fs.readFileSync(__dirname+'/../dist/index.html','utf8'),/id="characterSaveError"/);
const ctx={assert,console,AbortSignal,performance:{now:()=>0},setTimeout:noop,clearTimeout:noop,requestAnimationFrame:noop,localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},document:{getElementById:id=>els[id]??=el(),querySelectorAll:()=>[],createElement:el,addEventListener:noop,body:el()},window:{addEventListener:noop,matchMedia:()=>({matches:false})}};vm.createContext(ctx);
for(const f of ['cloud','loot','spirits','hud','systems','frontier','world','tutorial','skills','game'])vm.runInContext(fs.readFileSync(__dirname+'/../dist/'+f+'.js','utf8').replace(/boot\(\);\s*$/,''),ctx);
(async()=>{
ctx.fetch=async()=>({ok:false,status:401});await assert.rejects(vm.runInContext('initializeCloud()',ctx),error=>error.status===401);vm.runInContext('assert.equal(cloudReady,false)',ctx);
ctx.fetch=async()=>({ok:true,json:async()=>({account:'new-account',state:null,revision:0})});await vm.runInContext("s.character={name:'Other account'};initializeCloud()",ctx);vm.runInContext("assert.equal(s.character,null);assert.equal(cloudReady,true);queueCloudSave();assert.equal(cloudDirty,false);renderUI=()=>{};renderTutorial=()=>{};stop=()=>{};toast=()=>{};",ctx);
vm.runInContext("let creatorDraft={race:'elf',frame:'female',hair:1,topStyle:5,bottomStyle:4,topColor:2,bottomColor:7};assetsReady=true;",ctx);els.creator.open=true;ctx.fetch=async()=>({ok:false,status:503});await vm.runInContext("finishCharacter('Ember',2)",ctx);assert.equal(els.creator.open,true);assert.match(els.characterSaveError.textContent,/not saved/);
vm.runInContext('assert.equal(cloudDisconnected,true);cloudDisconnected=false;',ctx); // A reconnect starts a new online session.
let saved;ctx.fetch=async(url,options)=>{saved=JSON.parse(options.body);return {ok:true,json:async()=>({revision:1})}};await vm.runInContext("finishCharacter('Ember',2)",ctx);assert.equal(saved.state.character.name,'Ember');assert.equal(saved.state.character.race,'human');assert.equal(saved.state.character.frame,'female');assert.equal(saved.state.character.hair,1);assert.equal(saved.state.character.topStyle,5);assert.equal(saved.state.character.bottomStyle,4);assert.equal(els.creator.open,false);assert.equal(els.begin.disabled,false);
ctx.fetch=async()=>({ok:true,json:async()=>({account:'new-account',state:saved.state,revision:1})});await vm.runInContext('initializeCloud()',ctx);vm.runInContext("assert.equal(s.character.name,'Ember');assert.equal(s.character.topStyle,5);assert.equal(s.character.bottomStyle,4);assert.equal(cloudRevision,1)",ctx);
const oldSave=JSON.parse(JSON.stringify(saved.state));delete oldSave.skillProgressionVersion;oldSave.xp.Woodcutting=35*19**2;oldSave.xp.Worship=1260;ctx.fetch=async()=>({ok:true,json:async()=>({account:'old-account',state:oldSave,revision:7})});await vm.runInContext('initializeCloud()',ctx);vm.runInContext("assert.equal(s.character.name,'Ember');assert.equal(lv('Woodcutting'),20);assert.equal(s.xp.Worship,1260);assert.equal(s.skillProgressionVersion,1);assert.equal(cloudRevision,7)",ctx);
storage['emberfall-cloud-backup-v1']=JSON.stringify({account:'new-account',revision:1,pending:true,state:saved.state});ctx.fetch=async()=>({ok:true,json:async()=>({account:'new-account',state:{freshStart:'2026-09-11'},revision:2})});await vm.runInContext('initializeCloud()',ctx);vm.runInContext("assert.equal(s.character,null);assert.equal(cloudRevision,2);assert.equal(s.freshStart,'2026-09-11');",ctx);
storage['emberfall-cloud-backup-v1']=JSON.stringify({account:'new-account',revision:2,pending:true,state:saved.state});await vm.runInContext('initializeCloud()',ctx);vm.runInContext("assert.equal(s.character,null);",ctx);
vm.runInContext(`s=defaults();assert.deepEqual(Object.values(s.equipment).filter(Boolean),[]);assert.equal(Object.keys(s.gear).length,0);s.character={name:'Learner'};s.tutorial=tutorialSteps.findIndex(t=>t.event==='gear');chooseStyle('melee');assert.equal(tutorialStep().event,'dummy');assert.equal(s.equipment.weapon,null);s.tutorial=tutorialSteps.findIndex(t=>t.event==='magic');chooseStyle('magic');assert.equal(combatStyle(),'magic');assert.equal(s.equipment.weapon,null);s.tutorial=tutorialSteps.length-1;dialog=()=>{};tutorialEvent('talk-finish');assert.equal(s.bank.bronzeSword,1);assert.equal(s.tutorialReward,true);assert.equal(s.tutorialCasting,false);tutorialEvent('talk-finish');assert.equal(s.bank.bronzeSword,1);const legacy=defaults();legacy.starterGearVersion=undefined;legacy.gear={bronzeSword:1,leatherArmor:1};legacy.equipment={weapon:'bronzeSword',body:'leatherArmor'};normalizeJourney(legacy);assert.equal(legacy.equipment.weapon,null);assert.equal(legacy.gear.bronzeSword,0);`,ctx);
console.log('PASS: account errors, empty-account creation, failed-save recovery, confirmed creation, character reload, and legacy skill migration.');
})().catch(e=>{console.error(e);process.exitCode=1});
