const fs=require('fs'),vm=require('vm'),assert=require('assert');const root=__dirname+'/../dist/';const noop=()=>{};
function el(){return {style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},children:[],append(...children){this.children.push(...children)},appendChild(child){this.children.push(child)},replaceChildren(...children){this.children=children},removeAttribute:noop,show(){this.open=true},querySelectorAll:()=>[],set innerHTML(value){this.children=[]},listeners:{},addEventListener(type,fn){const before=this.listeners[type];this.listeners[type]=before?e=>{before(e);fn(e)}:fn},setPointerCapture:noop,setAttribute:noop,getContext:()=>new Proxy({},{get:()=>noop}),showModal(){this.open=true},close(){this.open=false},getBoundingClientRect:()=>({width:800,height:390,left:0,top:0})};}
const els={},data={},ctx={assert,console,atob,performance:{now:()=>0},setTimeout:noop,clearTimeout:noop,requestAnimationFrame:noop,localStorage:{getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v},document:{getElementById:id=>els[id]??=el(),querySelectorAll:()=>[],createElement:el,addEventListener:noop,body:el()},window:{addEventListener:noop,matchMedia:()=>({matches:false})}};vm.createContext(ctx);
for(const f of ['cloud','loot','spirits','hud','systems','trading','frontier','world','tutorial','skills','game'])vm.runInContext(fs.readFileSync(root+f+'.js','utf8').replace(/boot\(\);\s*$/,''),ctx,{filename:f});

vm.runInContext(fs.readFileSync(root+'view3d.js','utf8').replace(/boot\(\);\s*$/,''),ctx,{filename:'view3d'});
vm.runInContext(fs.readFileSync(root+'art-direction.js','utf8').replace(/boot\(\);\s*$/,''),ctx,{filename:'art-direction'});
vm.runInContext(fs.readFileSync(root+'renderer-gl.js','utf8').replace(/boot\(\);\s*$/,''),ctx,{filename:'renderer-gl'});
for(const f of ['kingdoms','realm-models','assets/briarhaven/models','briarhaven-art','assets/realms/models','realms-rebuilt','tree-identity','world-depth','organic-world','walk-in-world','world-style','building-orientation','assets/realms/monsters','creatures'])vm.runInContext(fs.readFileSync(root+f+'.js','utf8').replace(/boot\(\);\s*$/,''),ctx,{filename:f});
vm.runInContext(fs.readFileSync(root+'game-icons.js','utf8'),ctx);
vm.runInContext(fs.readFileSync(root+'equipment-interface.js','utf8'),ctx);

vm.runInContext(`
let randomSeed=91482;Math.random=()=>{randomSeed=(Math.imul(randomSeed,1664525)+1013904223)>>>0;return randomSeed/4294967296;};
renderAction=()=>{};draw=()=>{};drawPortrait=()=>{};setupExpandedWorld();setupSpirits();setupTutorialVillage();setupLoot();
s.character={name:'Fresh apprentice',look:0};s.tutorial=0;s.tutorialVersion=4;s.runEnabled=false;s.runEnergy=100;assetsReady=true;activateScene('overworld',42,51);
let testNow=0;Date.now=()=>testNow;function tick(){testNow+=50;if(tutorialStep()?.event==='monster'&&s.hp<=4&&s.bag.shrimp>0)eat();frame(testNow);}
function until(predicate,label){for(let i=0;i<3000;i++){if(predicate())return;tick();}throw new Error('Timed out: '+label+' @ '+s.x+','+s.y+' '+tutorialStep()?.event+' target '+target?.name+' path '+path.length);}
function current(event){assert.equal(tutorialStep()?.event,event);}
function clickDialog(label){const button=$('modalBody').children.find(b=>b.textContent===label&&b.onclick);assert(button,'dialog button '+label);button.onclick();}
function talk(role){current('talk-'+role);guide();until(()=>{if(!path.length&&!target&&!pendingWalkInDoor&&!$('modal').open)guide();return $('modal').open;},'reach '+role);clickDialog('Continue');}
function gather(event){current(event);guide();until(()=>{if(tutorialStep()?.event!==event)return true;if(!path.length&&!target&&!pendingWalkInDoor)guide();return false;},event);}
current('camera');observeTutorialCamera();view3d.yaw+=.3;tick();current('walk');walkTo(44,51);until(()=>tutorialStep()?.event!=='walk','walk anywhere');
talk('guide');current('bag');openTutorialPanel('bag');current('skills');openTutorialPanel('skills');
talk('woods');gather('tree');talk('fishing');gather('fish');assert(s.bag.rawShrimp>0);current('fire');assert(besideFishingTutor());assert(lightLog());current('cook-shrimp');assert(requestCookFish('rawShrimp'));until(()=>tutorialStep()?.event!=='cook-shrimp','cook shrimp by Nell');assert(s.bag.shrimp>0);talk('cooking');current('mix-dough');assert(s.bag.flour===1&&s.bag.jugWater===1);assert(mixBreadDough());gather('bake-bread');assert(s.bag.bread===1);assert((s.xp.Cooking||0)>=70);current('eat');eat();
talk('mining');gather('ore');gather('smelt');gather('smith');assert(s.gear.bronze_dagger===1);
talk('combat');current('equip-dagger');tutorialEvent('equip-dagger');current('equip-dagger');assert(equipItem('bronze_dagger'));current('combat-stats');openTutorialPanel('gear');current('combat-stats');paintEquipmentPreview=()=>{};guide();current('training-kit');close();guide();until(()=>$('modal').open,'training equipment');clickDialog('Take sword and shield');current('training-gear');assert(equipItem('woodenSword'));current('training-gear');assert(equipItem('woodenShield'));current('dummy');assert(s.gear.bronze_dagger===1);assert(s.tutorialGifts.combat);assert(s.tutorialGifts.combatFood);assert(s.bag.shrimp>=3);assert(grantTutorialItems('combat',{woodenSword:1,woodenShield:1}));assert.equal(s.gear.woodenSword,1);gather('dummy');gather('monster');current('loot');guide();until(()=>!path.length&&!target,'coins');guide();until(()=>tutorialStep()?.event!=='loot','bones');
assert(buryBones(),'the early burial shown in the recording');assert(s.tutorialActions.bury);s=JSON.parse(JSON.stringify(s));normalizeJourney(s);talk('bank');current('deposit');openBank();const bagBefore=s.gear.bronze_dagger;assert(transferBank('bronze_dagger'));current('withdraw');assert.equal(s.bank.bronze_dagger,1);assert(transferBank('bronze_dagger',true));assert.equal(s.gear.bronze_dagger,bagBefore);close();
talk('worship');current('spirit');guide();until(()=>$('modal').open,'Cinder');clickDialog('Form a bond');assert(s.spirits.cinder);assert(s.xp.Worship>=38);
talk('magic');current('magic');assert(s.gear.oakStaff===1);assert(s.tutorialGifts.magic);chooseStyle('magic');assert.equal(s.equipment.weapon,'oakStaff');const runesBefore=s.bag.runes;gather('magic');assert(s.bag.runes<runesBefore);assert(s.xp.Magic>0);
current('talk-finish');guide();until(()=>{if(!path.length&&!target&&!pendingWalkInDoor&&!$('modal').open)guide();return $('modal').open;},'Rowan finish');clickDialog('Finish apprenticeship');assert.equal(tutorialStep(),null);assert(s.tutorialReward);assert.equal(s.gear.woodenSword,1);assert.equal(s.gear.woodenShield,1);assert.equal(s.gear.oakStaff,1);assert(!s.bank.oakStaff,'earned staff is retained without duplication');close();
const completed=s.tutorial;s=JSON.parse(JSON.stringify(s));normalizeJourney(s);assert.equal(s.tutorial,completed);assert(s.spirits.cinder);assert.equal(s.gear.bronze_dagger,1);
// The recorded old save gets the new course without losing belongings or levels.
const legacy={...s,tutorial:0,tutorialVersion:undefined,x:14,y:18};const legacyXP=JSON.stringify(legacy.xp),legacyBag=JSON.stringify(legacy.bag);normalizeJourney(legacy,legacy);assert.equal(legacy.tutorial,0);assert.equal(JSON.stringify(legacy.xp),legacyXP);assert.equal(JSON.stringify(legacy.bag),legacyBag);
s.tutorial=2;activateScene('overworld',150,80);guide();assert($('modal').open);clickDialog('Return to Briarhaven');assert.equal(s.x,42);assert.equal(s.y,51);assert.equal(s.tutorial,2);
// Running changes real distance, consumes energy only while moving, and survives saving.
s.tutorial=tutorialSteps.length;activateScene('overworld',45,90);s.runEnabled=false;s.runEnergy=100;walkTo(45,100);const y0=py;for(let i=0;i<10;i++)advanceMovement(.05);const walking=py-y0;assert(Math.abs(walking-1)<.001,'walk speed');
activateScene('overworld',45,90);s.runEnabled=true;s.runEnergy=100;walkTo(45,100);for(let i=0;i<10;i++)advanceMovement(.05);assert(Math.abs(py-90-walking*2)<.001,'run covers twice the distance');assert(s.runEnergy<100);
stop();px=s.x;py=s.y;const energy=s.runEnergy;advanceMovement(.05);assert(s.runEnergy>energy,'rest recovers energy');
s.runEnergy=.001;walkTo(45,100);advanceMovement(.05);assert(!s.runEnabled,'empty energy switches to walking');assert(s.runEnergy>=0);s=JSON.parse(JSON.stringify(s));normalizeJourney(s);assert(!s.runEnabled);assert(s.runEnergy<1);
console.log('PASS: all 36 tutor-led lessons through real routes, conversations, gathering, crafting, combat, bank and spirit actions; recovery, saves, walking and running.');
`,ctx);
