const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{ctx}=require('../scripts/benchmark-desktop.cjs');ctx.assert=assert;
const timers=new Map();let timerId=0,nodes=0,plays=0;
class Param{constructor(){this.value=0;}setValueAtTime(v,t){assert(Number.isFinite(v+t));this.value=v;}exponentialRampToValueAtTime(v,t){assert(v>0&&Number.isFinite(v+t));this.value=v;}setTargetAtTime(v,t,k){assert(Number.isFinite(v+t+k));this.value=v;}cancelScheduledValues(){}}
const node=()=>{nodes++;return {gain:new Param(),frequency:new Param(),Q:new Param(),pan:new Param(),playbackRate:new Param(),threshold:new Param(),ratio:new Param(),connect(){},disconnect(){},start(){},stop(){}};};
class AudioContext{constructor(){this.currentTime=0;this.sampleRate=44100;this.state='suspended';this.destination={};}createGain(){return node();}createDynamicsCompressor(){return node();}createOscillator(){return node();}createBufferSource(){return node();}createBiquadFilter(){return node();}createStereoPanner(){return node();}createMediaElementSource(){return node();}createBuffer(channels,length){const data=new Float32Array(length);return {getChannelData:()=>data};}decodeAudioData(bytes){assert(bytes.byteLength);return Promise.resolve({duration:.5});}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}}
class Audio{constructor(){this.paused=true;}play(){plays++;this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
let downloads=0;ctx.fetch=async()=>{downloads++;return {ok:true,arrayBuffer:async()=>new ArrayBuffer(16)};};ctx.downloadCount=()=>downloads;ctx.window.AudioContext=AudioContext;ctx.Audio=Audio;ctx.realmAssetURL=p=>p;ctx.setTimeout=fn=>{timers.set(++timerId,fn);return timerId;};ctx.clearTimeout=id=>timers.delete(id);ctx.runAudioTimers=()=>{for(const [id,fn]of timers){timers.delete(id);fn();}};ctx.nodeCount=()=>nodes;ctx.playCount=()=>plays;
for(const f of ['trading','world-options','item-use','tutorial-island','npc-dialogue','realm-story','lairs','encounters','game-audio'])vm.runInContext(fs.readFileSync('dist/'+f+'.js','utf8'),ctx,{filename:f});
vm.runInContext(`{
save=()=>{};s.character=null;s.sound=true;currentScene='tutorial';
assert.equal(gameAudio.context,null,'no audio or music download before a gesture');unlockGameAudio();assert.equal(gameAudio.context.state,'running');assert.equal(gameAudio.current,'title');assert.equal(gameAudio.tracks.size,1);assert.equal(gameAudio.tracks.get('title').element.preload,'none');assert(gameAudio.tracks.get('title').element.loop);assert.equal(downloadCount(),0);s.character={name:'Audio check'};$('creator').open=true;updateAreaMusic();assert.equal(gameAudio.current,'title');$('creator').open=false;updateAreaMusic();assert.equal(gameAudio.current,'hero');
const cues=['step','wood','mine','smith','fish','cook','fire','sword','bow','magic','spirit','teleport','hit','hurt','miss','door','coins','bank','equip','eat','bury','craft','quest','questComplete','level','levelRise','lesson','lowHealth','click','fishCast','phase'];
for(const cue of cues){const before=nodeCount();gameAudio.context.currentTime+=3;playGameSound(cue);assert(nodeCount()>before,cue+' produces finite audio nodes');runAudioTimers();assert.equal(gameAudio.voices,0,'finished voices are released');}
for(const element of ['Fire','Water','Air','Earth']){const n=nodeCount();playSpiritBondSound(element);assert(nodeCount()>n,'elemental awakening sound');}
const before=nodeCount();s.audio.effects=0;playGameSound('wood');assert.equal(nodeCount(),before,'effects volume zero is silent');s.audio.effects=.65;
currentScene='overworld';regionInfo=()=>['Briarhaven','Village'];settlementAt=()=>null;updateAreaMusic();assert.equal(gameAudio.current,'town');assert.equal(gameAudio.tracks.size,3);
currentScene='mine';updateAreaMusic();assert.equal(gameAudio.current,'danger');assert.equal(gameAudio.tracks.size,4);currentScene='overworld';regionInfo=()=>['Wild fields',''];updateAreaMusic();assert.equal(gameAudio.current,'refuge');activeEncounter={o:{encounter:'king'}};updateAreaMusic();assert.equal(gameAudio.current,'hero');activeEncounter={o:{kind:'rat'}};updateAreaMusic();assert.equal(gameAudio.current,'refuge');activeEncounter=null;currentScene='mine';updateAreaMusic();const streams=gameAudio.tracks.size;updateAreaMusic();assert.equal(gameAudio.tracks.size,streams,'repeated updates reuse music streams');
toggleAmbient();runAudioTimers();assert.equal(s.sound,false);assert.equal(gameAudio.master.gain.value,0);assert([...gameAudio.tracks.values()].every(t=>t.element.paused));const silentNodes=nodeCount();playGameSound('magic');assert.equal(nodeCount(),silentNodes);
toggleAmbient();assert.equal(s.sound,true);assert.equal(gameAudio.current,'danger');document.hidden=true;const hiddenNodes=nodeCount();playGameSound('step');assert.equal(nodeCount(),hiddenNodes);
document.hidden=false;const realPlay=playGameSound,sounded=[];playGameSound=kind=>sounded.push(kind);const tree={type:'tree',x:px,y:py};for(let swing=0;swing<4;swing++){soundGatheringSwing(tree,0,.3,1);soundGatheringSwing(tree,.3,.5,1);soundGatheringSwing(tree,.5,.8,1);soundGatheringSwing(tree,.8,1,1);}assert.equal(sounded.filter(k=>k==='wood').length,4,'each failed or successful swing sounds exactly once before its harvest roll');soundGatheringSwing(tree,0,1,1);assert.equal(sounded.filter(k=>k==='wood').length,5,'a frame crossing the contact point still plays');playGameSound=realPlay;console.log('PASS: 30 sound cues, finite envelopes, released nodes, mute/background behavior, gathering impact timing, login/creator/tutorial/boss/area transitions, and five reusable music streams.');
}`,ctx);

(async()=>{await vm.runInContext(`(async()=>{const first=loadSoundSample('wood-1');assert.equal(first,loadSoundSample('wood-1'));await first;assert(soundBuffers.has('wood-1'));gameAudio.context.currentTime+=3;const before=nodeCount();playGameSound('wood');assert(nodeCount()>before,'decoded recorded foley plays');runAudioTimers();assert.equal(gameAudio.voices,0);})()`,ctx);console.log('PASS: recorded foley decoding, request deduplication and sample playback.');})().catch(e=>{console.error(e);process.exitCode=1;});
