const fs=require('fs');
const bootstrap=fs.readFileSync('tests/apprenticeship.cjs','utf8').split('\nvm.runInContext(`\nlet randomSeed')[0].replace("const root=__dirname+'/../dist/'","const root=process.cwd()+'/dist/'");
eval(bootstrap+`\nvm.runInContext(\`
setupExpandedWorld();setupSpirits();setupTutorialVillage();s.tutorialReward=true;s.tutorial=tutorialSteps.length;activateScene('overworld',42,51);assetsReady=true;
assert.equal(roadInfluence(55,61).length,3,'terrain road channels');
const townRooms=buildings.filter(b=>b.settlement==='briarhaven');assert.equal(townRooms.length,6);
for(const b of townRooms){const approach=doorApproach(b.service,false);assert(route(...approach,false),'reachable entrance '+b.name+' '+approach+' obstacles '+JSON.stringify(objects.filter(o=>Math.hypot(o.x-approach[0],o.y-approach[1])<2).map(o=>[o.name,o.x,o.y])));setWalkInDoor(b.service,true,true);for(const o of objects.filter(o=>o.interiorBuilding===b.service.destination&&['villager','banker','shop','inn','forge','range'].includes(o.type)))assert(route(o.x,o.y,true,1.45),'reachable service '+o.name);}
const rats=worldScenes.tutorial.objects.filter(o=>o.penId);assert(rats.length>=15,'island rat pen remains intact');
const goblins=objects.filter(o=>o.briarhavenGoblin);assert.equal(goblins.length,15);for(const o of goblins){assert(!water(o.x,o.y),'goblin on dry land');assert(route(o.x,o.y,true),'goblin village reachable');assert(!trainingRatCanMove(o,83,99));assert(!trainingRatCanMove(o,95,111));assert(trainingRatCanMove(o,o.homeX,o.homeY));}
const before=goblins.map(o=>[o.x,o.y]);s.x=px=95;s.y=py=97;for(let i=0;i<200;i++){livingWorld(.1);for(const o of goblins){o.drawX=o.x;o.drawY=o.y;assert(trainingRatCanMove(o,o.x,o.y));}}assert(goblins.some((o,i)=>o.x!==before[i][0]||o.y!==before[i][1]),'goblins roam');
for(const yaw of [0,.5,Math.PI/2,Math.PI,-2]){view3d.yaw=yaw;for(const [x,y]of [[95,97],[99,98],[91,93]]){const p=minimapPoint(x,y),tile=minimapTile(p[0]/300,p[1]/300);assert.equal(tile[0],x);assert.equal(tile[1],y);}}
s.x=px=1;s.y=py=1;const centre=minimapPoint(px,py);assert.equal(centre[0],150);assert.equal(centre[1],150);
activateScene('overworld',55,64);s.bag={normalLogs:2};s.toolBelt.tinderbox=true;s.xp.Firemaking=0;Math.random=()=>0;const fireXp=s.xp.Firemaking;assert(lightLog('normalLogs'));assert(!objects.some(o=>o.type==='camp'&&o.x===s.x&&o.y===s.y));const dropped=playerAction.pile;stop();assert(dropped.items.normalLogs===1&&s.groundLoot.includes(dropped));assert.equal(s.xp.Firemaking,fireXp);
assert(lightLog('normalLogs'));time+=2.5;updatePlayerAction();assert.equal(s.xp.Firemaking,TREE_RESOURCES.normal.fire);assert(path.length===1,'step away when fire catches');const fire=objects.find(o=>o.type==='camp'&&o.x===s.x&&o.y===s.y);assert(fire);const [ex,ey]=path[0];stop();s.x=px=ex;s.y=py=ey;s.bag.rawShrimp=2;s.xp.Cooking=0;Math.random=()=>.99;assert(cookFish('rawShrimp',false,fire));assert.equal(playerAction.kind,'cook');stop();assert.equal(s.bag.rawShrimp,2);assert(cookFish('rawShrimp',false,fire));time+=1;updatePlayerAction();assert.equal(s.bag.rawShrimp,1);assert.equal(s.bag.shrimp,1);const gained=s.xp.Cooking;updatePlayerAction();assert.equal(s.xp.Cooking,gained,'cook commits once');
console.log('PASS: all six mainland entrances and services, 15 reachable roaming goblins, island preservation, rotated minimap round-trips, fire cancellation and delayed cooking.');
\`,ctx);`);
