const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const handlers={},documentEvents={},windowEvents={},elements={};let hold=null,clicks=0,menus=0,walks=0,prevented=0;
const noop=()=>{},el=id=>elements[id]??={open:false,handlers:{},setAttribute(k,v){this[k]=v},addEventListener(k,fn){this.handlers[k]=fn}};
const context={assert,console,Map,Math,Set,assetsReady:true,cloudConflict:false,cloudDisconnected:false,document:{activeElement:null,addEventListener:(k,fn)=>documentEvents[k]=fn},window:{addEventListener:(k,fn)=>windowEvents[k]=fn},canvas:{addEventListener:(k,fn)=>handlers[k]=fn,setPointerCapture:noop},$:el,setTimeout:fn=>(hold=fn,1),clearTimeout:()=>hold=null,openWorldOptions:()=>menus++,clickWorld3:()=>clicks++,rememberView:()=>context.syncCameraZoom(),view3d:{yaw:0,tilt:.5,zoom:92,min:58,max:132},cameraDefault3:{yaw:-2.05,tilt:.27,zoom:118},eat:noop,toggleRun:noop,walkTo:()=>walks++,select:()=>walks++};
vm.createContext(context);let source=fs.readFileSync('dist/view3d.js','utf8');
// Saved perspective views remain bounded to the closer third-person range.
for(const [saved,expected]of [[14,58],[42,58],[58,58],[95,95],[150,132]]){const restored=vm.runInNewContext(source.slice(0,source.indexOf('function syncCameraZoom'))+';view3d',{localStorage:{getItem:()=>JSON.stringify({zoom:saved})}});assert.equal(restored.min,58);assert.equal(restored.zoom,expected);}
vm.runInContext(source.slice(source.indexOf('function syncCameraZoom'),source.indexOf('function rememberView')),context);vm.runInContext(source.slice(source.indexOf('const cameraPointers=new Map()')),context);
source=fs.readFileSync('dist/game.js','utf8');const keyStart=source.indexOf("document.addEventListener('keydown',e=>{");vm.runInContext(source.slice(keyStart,source.indexOf('\nasync function boot',keyStart)),context);
for(const [percent,zoom]of [[0,132],[50,95],[100,58]]){el('cameraZoom').handlers.input({target:{value:String(percent)}});assert(Math.abs(context.view3d.zoom-zoom)<1e-9);assert.equal(el('cameraZoomValue').textContent,percent+'%');}context.view3d.zoom=95;
const e={pointerId:1,button:0,pointerType:'touch',clientX:100,clientY:100,preventDefault(){prevented++}};
handlers.pointerdown(e);handlers.pointermove({...e,clientX:103});handlers.pointerup({...e,clientX:103});assert.equal(clicks,1);assert.equal(context.view3d.yaw,0,'tap jitter does not rotate');
handlers.pointerdown(e);const touchTilt=context.view3d.tilt;handlers.pointermove({...e,clientX:145,clientY:120});assert.equal(hold,null);assert(context.view3d.yaw>0);assert(context.view3d.tilt>touchTilt,'vertical one-finger drag adjusts the camera angle');handlers.pointerup({...e,clientX:145,clientY:120});assert.equal(clicks,1,'one-finger swipe never walks');
const mouse={...e,pointerId:3,pointerType:'mouse'};handlers.pointerdown(mouse);handlers.pointermove({...mouse,clientX:145,clientY:120});assert(context.view3d.tilt>touchTilt,'mouse drag retains pitch control');handlers.pointerup({...mouse,clientX:145,clientY:120});
handlers.pointerdown(e);handlers.pointerup({...e,clientX:180});assert.equal(clicks,1,'a displaced release without a move event is not a tap');
handlers.pointerdown(e);handlers.pointerdown({...e,pointerId:2,clientX:180});const beforePinch={...context.view3d};handlers.pointermove({...e,pointerId:2,clientX:240});assert(context.view3d.zoom>beforePinch.zoom);assert.equal(context.view3d.yaw,beforePinch.yaw,'pinch is zoom only');handlers.pointerup({...e,pointerId:2,clientX:240});handlers.pointermove({...e,clientX:150});assert.equal(context.view3d.yaw,beforePinch.yaw,'remaining pinch finger cannot jump the camera');handlers.pointerup({...e,clientX:150});assert.equal(clicks,1);
// Neither mouse wheel nor touch pinch nor retained buttons can exceed the cap.
handlers.wheel({deltaY:10000,preventDefault:noop});assert.equal(context.view3d.zoom,58);assert.equal(el('cameraZoomValue').textContent,'100%');
el('zoomOut').onclick();assert.equal(context.view3d.zoom,58);
handlers.wheel({deltaY:-10000,preventDefault:noop});assert.equal(context.view3d.zoom,132);el('zoomIn').onclick();assert.equal(context.view3d.zoom,132);
handlers.pointerdown(e);handlers.pointerdown({...e,pointerId:2,clientX:200});handlers.pointermove({...e,pointerId:2,clientX:101});assert.equal(context.view3d.zoom,58);assert.equal(el('cameraZoomValue').textContent,'100%');handlers.pointerup({...e,pointerId:2});handlers.pointerup(e);
el('cameraReset').onclick();assert.equal(context.view3d.zoom,118);assert.equal(context.view3d.tilt,.27);assert.equal(el('cameraZoomValue').textContent,'19%');
handlers.pointerdown(e);hold();handlers.pointermove({...e,clientX:160});handlers.pointerup({...e,clientX:160});assert.equal(menus,1);assert.equal(clicks,1,'hold menu suppresses movement');
handlers.pointerdown(e);handlers.pointercancel(e);handlers.pointerup(e);handlers.pointerdown(e);handlers.pointerup(e);assert.equal(clicks,2,'cancelled gestures release cleanly');
const key=(name,target=null,more={})=>documentEvents.keydown({key:name,target,preventDefault(){prevented++},...more});
for(const name of ['w','a','s','d','W','A','S','D']){const n=prevented;key(name);assert.equal(prevented,n,'typing '+name+' remains unconsumed');}assert.equal(walks,0);
const yaw=context.view3d.yaw;key('ArrowLeft');vm.runInContext('updateCameraKeys(.1)',context);assert(context.view3d.yaw<yaw);documentEvents.keyup({key:'ArrowLeft'});const released=context.view3d.yaw;vm.runInContext('updateCameraKeys(.1)',context);assert.equal(context.view3d.yaw,released);
const pitch=context.view3d.tilt;key('ArrowUp');vm.runInContext('updateCameraKeys(.1)',context);assert(context.view3d.tilt<pitch);windowEvents.blur();assert.equal(walks,0,'arrow keys never move the player');
const editable={closest:()=>({})},still={...context.view3d};key('ArrowRight',editable);vm.runInContext('updateCameraKeys(.1)',context);assert.equal(context.view3d.yaw,still.yaw,'input arrow keys remain text navigation');
el('modal').open=true;key('ArrowLeft');vm.runInContext('updateCameraKeys(.1)',context);assert.equal(context.view3d.yaw,still.yaw,'dialogs pause keyboard orbit');
assert(!/id="(?:cameraLeft|cameraRight|creatorLeft|creatorRight)"/.test(fs.readFileSync('dist/index.html','utf8')));
const beforeCaptureFailure=clicks;context.canvas.setPointerCapture=()=>{throw new Error('WebKit pointer capture unavailable')};handlers.pointerdown(e);handlers.pointerup(e);assert.equal(clicks,beforeCaptureFailure+1,'an iPhone tap still moves when WebKit rejects pointer capture');
console.log('PASS: saved zoom migration, slider/wheel/pinch/button limits, reset readout, touch and mouse pitch, pinch zoom, hold/cancel, held arrow keys, input focus, modal guards and unconsumed WASD.');
