const fs=require('fs');
const bootstrap=fs.readFileSync('tests/apprenticeship.cjs','utf8').split('\nvm.runInContext(`\nlet randomSeed')[0].replace("const root=__dirname+'/../dist/'","const root=process.cwd()+'/dist/'");
eval(bootstrap+`\nctx.setInterval=()=>{};ctx.AbortSignal=AbortSignal;ctx.fetch=async()=>({ok:true,json:async()=>({})});ctx.document.querySelector=()=>null;ctx.devicePixelRatio=1;
// Retain controls when moving them between panels, as the browser DOM does.
const originalElement=el;function movable(){const node=originalElement();node.style.setProperty=()=>{};node.getAttribute=k=>node[k]||'';node.setAttribute=(k,v)=>node[k]=v;node.prepend=(...nodes)=>{for(const n of nodes){if(n.parentElement)n.parentElement.children=n.parentElement.children.filter(c=>c!==n);n.parentElement=node;}node.children.unshift(...nodes);};node.appendChild=child=>{if(child.parentElement)child.parentElement.children=child.parentElement.children.filter(c=>c!==child);child.parentElement=node;node.children.push(child);if(child.id)els[child.id]=child;return child;};node.append=(...nodes)=>nodes.forEach(n=>node.appendChild(n));node.querySelector=()=>movable();node.options=[];return node;}ctx.document.createElement=movable;for(const [id,node]of Object.entries(els)){Object.assign(node,{appendChild:movable().appendChild});}ctx.document.getElementById=id=>els[id]??=movable();ctx.document.body.style.setProperty=()=>{};
vm.runInContext(fs.readFileSync('dist/account-auth.js','utf8'),ctx);vm.runInContext("accountUsername='alice';",ctx);
vm.runInContext(fs.readFileSync('dist/game-messages.js','utf8'),ctx);vm.runInContext("gameMessage('Message before chat loads');",ctx);
vm.runInContext(fs.readFileSync('dist/multiplayer.js','utf8'),ctx);vm.runInContext(fs.readFileSync('dist/social.js','utf8'),ctx);
// Use movable elements for controls created by the fixture before the shell mounts.
for(const id of ['combatbar','friendsPane','fullscreenButton','cameraControls','ambientButton','waveButton','journal','tutorial','gameTabs','mapHud','panel','gameDock','hitpointOrb','worshipOrb','coinPouchOrb'])els[id]=movable();
ctx.navigator={};els.game=movable();els.game.appendChild(els.fullscreenButton);const zoomControl=els.cameraControls;els.game.appendChild(zoomControl);ctx.zoomControl=zoomControl;
vm.runInContext(fs.readFileSync('dist/play-display.js','utf8'),ctx);
// Mirror the real document: spiritButton starts inside gameTabs, and an ID
// lookup cannot find a node after replaceChildren disconnects it.
const spiritControl=els.spiritButton||movable();els.spiritButton=spiritControl;
els.gameTabs.appendChild(spiritControl);
els.gameTabs.replaceChildren=()=>{for(const child of els.gameTabs.children)child.parentElement=null;els.gameTabs.children=[];};
const lookup=ctx.document.getElementById;
ctx.document.getElementById=id=>id==='spiritButton'&&!spiritControl.parentElement?null:lookup(id);
vm.runInContext(fs.readFileSync('dist/render-diagnostics.js','utf8'),ctx);vm.runInContext(fs.readFileSync('dist/classic-ui.js','utf8'),ctx);
vm.runInContext(\`
assert($('chatMessages').children.some(p=>p.textContent==='Message before chat loads'),'early game notices retained');
assert.equal($('gameTabs').children.length,10);for(const button of $('gameTabs').children){assert(button.children.some(n=>n.className==='journal-tab-label'&&n.textContent),'navigation has visible labels');button.children=[];setHudButton(button,'Refreshed icon','bag');assert(button.children.some(n=>n.className==='journal-tab-label'&&n.textContent),'labels survive icon refresh');}assert(!CLASSIC_TABS.some(t=>t[0]==='tools'),'Tool belt stays inside Equipment');assert.equal(CLASSIC_TABS.find(t=>t[0]==='settings')[1],'settings');assert(!CLASSIC_TABS.some(t=>['account','emotes','music'].includes(t[0])));assert.equal($('runButton').parentElement,$('mapHud'));assert.equal($('spiritButton').parentElement,$('mapHud'));
assert.equal($('cameraControls'),zoomControl);assert.equal(zoomControl.parentElement,classicStorage,'camera controls start off the gameplay screen');
s.character={name:'Alice',look:0};s.spirits={};assetsReady=false;
for(const mobile of [false,true]){window.matchMedia=q=>({matches:mobile&&['(pointer: coarse)','(max-width: 760px)'].includes(q)});updateClassicLayout();for(const which of ['friends','ignore','settings','worship','combat']){tab=which;renderPanel();assert($('panel').children.length>0,which+' renders');assert.equal($('fullscreenButton').parentElement,$('game'),'fullscreen stays on the game screen across every panel');assert.equal($('fullscreenButton').hidden,false,'browser fullscreen stays visible');assert.equal($('cameraControls'),zoomControl,'same camera control survives panel switches');assert.equal(zoomControl.parentElement,which==='settings'?$('panel'):classicStorage,'zoom slider appears only in Settings');if(which==='settings'){assert($('panel').children.some(b=>b.onclick===logoutGame),'logout lives in Settings');const setting=$('fullscreenSettingsButton');assert.equal(setting.parentElement,$('panel'));assert.equal(setting.onclick,togglePlayFullscreen);assert.equal(setting.getAttribute('aria-label'),'Enter fullscreen');}}}
tab='spells';renderPanel();assert.equal(classicSpellPage,'combat');let pages=$('panel').children.find(n=>n.className==='classic-spell-pages');pages.children.find(b=>b.dataset.spellPage==='teleports').onclick();assert.equal(classicSpellPage,'teleports');const home=$('panel').children.find(n=>n.className==='classic-spell-grid').children[0];assert.equal(home.dataset.spellId,'homeTeleport');assert(home.title.includes('No relics')&&home.title.includes('No XP'));assert.equal(home.onclick,beginHomeTeleport);pages=$('panel').children.find(n=>n.className==='classic-spell-pages');pages.children[0].onclick();assert.equal($('panel').children.find(n=>n.className==='classic-spell-grid').children.length,Object.keys(SPELLS).length,'combat spells retained');
assert.equal(typeof $('fullscreenButton').listeners.click,'function');
tab='friends';renderPanel();assert.equal($('friendsPane').parentElement,$('panel'));openSocial();assert.equal($('friendsPane').hidden,false,'chat and friends remain usable together');tab='settings';renderPanel();assert.equal($('friendsPane').parentElement,classicStorage,'friends control survives panel changes');
const before=$('chatMessages').children.length;toast('Your bag is full.');assert.equal($('chatMessages').children.length,before+1);assert.equal($('chatMessages').children.at(-1).textContent,'Your bag is full.');
assert.equal($('mapHud').children.filter(b=>b.id==='coinPouchOrb').length,1);assert(!$('mapHud').children.some(b=>b.id==='specialOrb'));s.gold=2500;updateClassicVitals();assert.equal($('coinPouchValue').textContent,'2,500');assert.equal($('hitpointValue').textContent,s.hp+' / '+maxhp());s.spirits.brook={state:'set'};updateClassicVitals();assert.equal($('hitpointValue').dataset.label,'Health · +4 Brook');assert.equal($('hitpointValue').textContent,s.hp+' / '+(lv('Hitpoints')+4));assert($('hitpointOrb').title.includes('from Brook'));assert.equal($('hitpointOrb').onclick,showHealthDetails);s.spirits={};assert.equal($('worshipValue').textContent,lv('Worship'));
console.log('PASS: camera slider retained in Settings across desktop/mobile panel changes; persistent browser fullscreen on desktop/mobile with an independent settings control; ten wired tabs with Tool belt excluded, preserved controls across panel switches, chat alongside friends, early notices, chat-only toast messages, and live map vitals.');
\`,ctx);`);
