const fs=require('fs'),vm=require('vm'),assert=require('assert');const root=__dirname+'/../dist/';const noop=()=>{};
function el(){return {style:{},dataset:{},classList:{add:noop,remove:noop,toggle:noop,contains:()=>false},appendChild:noop,querySelectorAll:()=>[],addEventListener:noop,setAttribute:noop,getContext:()=>new Proxy({},{get:()=>noop}),showModal(){this.open=true},close(){this.open=false},getBoundingClientRect:()=>({width:800,height:390,left:0,top:0})};}
const els={},data={},ctx={assert,console,performance:{now:()=>0},setTimeout:noop,clearTimeout:noop,requestAnimationFrame:noop,localStorage:{getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v},document:{getElementById:id=>els[id]??=el(),querySelectorAll:()=>[],createElement:el,addEventListener:noop,body:el()},window:{addEventListener:noop,matchMedia:()=>({matches:false})}};vm.createContext(ctx);
for(const f of ['cloud','loot','spirits','hud','systems','frontier','world','tutorial','skills','game'])vm.runInContext(fs.readFileSync(root+f+'.js','utf8').replace(/boot\(\);\s*$/,''),ctx,{filename:f});
vm.runInContext(`renderUI=()=>{};renderAction=()=>{};renderTutorial=()=>{};setupExpandedWorld();setupSpirits();setupLoot();assert.equal(tutorialSteps.length,38);assert.equal(sceneSize()[0],96);
for(const [id,def]of Object.entries(SPIRITS)){activateScene(def.scene);assert(route(def.x,def.y,true,1.45)!==null,id);}
activateScene('overworld',75,62);for(const [x,y]of [[71,62],[79,62],[87,71],[90,35]])assert(route(x,y,true,1.45)!==null);assert(worldScenes.stoneInn);assert(worldScenes.stoneShop);
s.bag={logs:0,fish:0,arrows:0,runes:0};s.gear={bronzeSword:1};s.equipment={weapon:'bronzeSword',head:null,body:null,feet:null,shield:null};assert.equal(inventorySlots().length,0);assert(addToBag('logs',25));assert(!addToBag('fish'));assert(!unequipItem('weapon'));s.bag.logs--;assert(unequipItem('weapon'));assert.equal(inventorySlots().length,25);assert(equipItem('bronzeSword'));assert.equal(inventorySlots().length,24);
s.bag.logs=0;assert(addToBag('arrows',100));assert(addToBag('arrows',50));assert.equal(inventorySlots().length,1);
s.groundLoot=[];const gold=s.gold;for(const kind of ['wolf','goblin','slime','rat','skeleton','bandit','man','king','warden','ridgewolf','sentinel'])monsterDrop({kind,x:20,y:20,coins:7});assert.equal(s.gold,gold);assert.equal(s.bag.bones,undefined);const pile=s.groundLoot[0];assert(takeGroundItem(pile,'coins'));assert.equal(carriedCoins(),gold+77);assert(takeGroundItem(pile,'bones'));assert(s.bag.bones>0);
s.frontier={quest:1,accepted:true,kills:0};for(let i=0;i<4;i++)frontierKill({kind:'ridgewolf'});assert.equal(s.frontier.kills,4);
s.spirits={cinder:{state:'set',recovery:0},brook:{state:'set',recovery:0}};assert.equal(spiritBonus('melee'),2);assert.equal(spiritBonus('health'),8);s.spirits.cinder={state:'recovery',recovery:30};updateSpirits(30);assert.equal(s.spirits.cinder.state,'set');
console.log('PASS: new routes, tutorial, inventory capacity, worn gear, ground drops, pickup, quests and spirit recovery.');`,ctx);
for(const [,f]of fs.readFileSync(root+'index.html','utf8').matchAll(/(?:src|href)="([^"#]+)"/g))if(!f.includes('://'))assert(fs.existsSync(root+f),f);
for(const f of ['heroes','monsters','environment','items','terrain','characters','poses','walking','spirits'])assert(fs.existsSync(root+'assets/'+f+'.png'));
