import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {handleSave,handleAuth,SAVE_RESET_VERSION} from '../worker/api.js';
const db=new DatabaseSync(':memory:');
for(const name of fs.readdirSync('drizzle').filter(name=>name.endsWith('.sql')&&!name.startsWith('0005')).sort())db.exec(fs.readFileSync('drizzle/'+name,'utf8'));
const env={DB:{prepare(sql){return{bind(...args){return{async first(){return db.prepare(sql).get(...args)},async all(){return{results:db.prepare(sql).all(...args)}},async run(){return{meta:{changes:db.prepare(sql).run(...args).changes}}}}}}}}};
const request=(path,method='GET',cookie='',body)=>new Request('https://game.test'+path,{method,headers:{cookie,origin:'https://game.test'},...(body?{body:JSON.stringify(body)}:{})});
const registered=await handleAuth(request('/api/auth/register','POST','',{username:'reset_tester',password:'abcde'}),env);assert.equal(registered.status,200);const cookie=registered.headers.get('set-cookie').split(';')[0];
const account=db.prepare('SELECT * FROM game_accounts').get(),sessions=db.prepare('SELECT * FROM game_sessions').all();
const old={character:{name:'Veteran'},xp:{Attack:100000},bag:{runeBar:50},bank:{fish:200},gold:9999,spirits:{cinder:true},x:40,y:50,hp:40};
for(const [id,rev]of [['account:'+account.id,9],['player-b',1],['guest:abc',4]])db.prepare('INSERT INTO character_saves VALUES (?,?,?,?)').run(id,JSON.stringify(old),rev,'before-reset');
db.prepare('INSERT INTO player_presence VALUES (?,?,?,?)').run('old-presence','overworld','{}',Date.now());
db.exec(fs.readFileSync('drizzle/0005_creator_account_reset.sql','utf8'));
assert.equal(db.prepare('SELECT account_count FROM game_resets WHERE reset_id=?').get(SAVE_RESET_VERSION).account_count,3);
assert.equal(db.prepare('SELECT count(*) AS n FROM player_presence').get().n,0);
for(const row of db.prepare('SELECT * FROM character_saves').all())assert.deepEqual(JSON.parse(row.state),{freshStart:SAVE_RESET_VERSION});
assert.equal(db.prepare('SELECT revision FROM character_saves WHERE user_id=?').get('account:'+account.id).revision,10);
assert.deepEqual(db.prepare('SELECT * FROM game_accounts').get(),account,'username and password hash preserved');assert.deepEqual(db.prepare('SELECT * FROM game_sessions').all(),sessions,'existing session preserved');
const loaded=await (await handleSave(request('/api/character','GET',cookie),env)).json();assert.equal(loaded.state.freshStart,SAVE_RESET_VERSION);assert.equal(loaded.revision,10);
const stale=await handleSave(request('/api/character','PUT',cookie,{revision:10,state:old,resetVersion:'2026-09-12-all-accounts-1'}),env);assert.equal(stale.status,409);assert.equal((await stale.json()).code,'ACCOUNTS_RESET','old tabs cannot restore wiped progress');
assert.equal((await handleAuth(request('/api/auth/login','POST','',{username:'reset_tester',password:'abcde'}),env)).status,200,'same five-character password still logs in');
console.log('PASS: all character progress reset, audit count, increasing revisions, cleared presence, preserved login/session and rejected old-tab saves.');
