import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {handleSave,SAVE_RESET_VERSION} from '../worker/api.js';
const db=new DatabaseSync(':memory:');
for(const name of ['0000_amazing_black_bolt.sql','0001_overjoyed_warbird.sql'])db.exec(fs.readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));
const old={character:{name:'Veteran'},xp:{Attack:100000},bag:{runeBar:50},bank:{fish:200},gold:9999,spirits:{cinder:true},x:40,y:50,hp:40};
for(const [id,rev]of [['player-a',9],['player-b',1],['guest:abc',4]])db.prepare('INSERT INTO character_saves VALUES (?,?,?,?)').run(id,JSON.stringify(old),rev,'before-reset');
db.prepare('INSERT INTO player_presence VALUES (?,?,?,?)').run('old-presence','overworld','{}',Date.now());
db.exec(fs.readFileSync(new URL('../drizzle/0003_all_accounts_fresh_start.sql',import.meta.url),'utf8'));
assert.equal(db.prepare('SELECT account_count FROM game_resets').get().account_count,3);
assert.equal(db.prepare('SELECT count(*) AS n FROM player_presence').get().n,0);
for(const row of db.prepare('SELECT * FROM character_saves').all())assert.deepEqual(JSON.parse(row.state),{freshStart:SAVE_RESET_VERSION});
assert.equal(db.prepare("SELECT revision FROM character_saves WHERE user_id='player-a'").get().revision,10);
console.log('PASS: all legacy accounts reset, audit count recorded, revisions increased, and presence cleared.');
