import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {handleAuth} from '../worker/auth.js';
const database=new DatabaseSync(':memory:');
database.exec('CREATE TABLE game_accounts(id TEXT PRIMARY KEY,username TEXT,normalized_username TEXT UNIQUE,password_hash TEXT,created_at INTEGER); CREATE TABLE game_sessions(token_hash TEXT PRIMARY KEY,account_id TEXT,expires_at INTEGER); CREATE TABLE auth_limits(key TEXT PRIMARY KEY,window INTEGER,attempts INTEGER);');
database.exec(readFileSync(new URL('../drizzle/0009_vengeful_white_queen.sql',import.meta.url),'utf8'));
const env={DB:{prepare(sql){
 return {bind(...args){
  return {async first(){return database.prepare(sql).get(...args)||null;},async run(){return {meta:{changes:database.prepare(sql).run(...args).changes}};}};
 }};
}}};
const auth=(action,body,cookie)=>handleAuth(new Request('https://veldren.test/api/auth/'+action,{method:body?'POST':'GET',headers:{Origin:'https://veldren.test',...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})}),env);
let response=await auth('register',{username:'NewHero',password:'1234'});assert.equal(response.status,400);assert.match((await response.json()).error,/5 characters/);
response=await auth('register',{username:'NewHero',password:'12345'});assert.equal(response.status,200);const first=await response.json(),cookie=response.headers.get('set-cookie').split(';')[0];assert.equal(first.account.username,'NewHero');assert.match(response.headers.get('set-cookie'),/HttpOnly/);
assert.notEqual(database.prepare('SELECT password_hash FROM game_accounts').get().password_hash,'12345');
response=await auth('session',null,cookie);assert.equal((await response.json()).account.username,'NewHero','registration immediately signs into the new account');
response=await auth('register',{username:'newhero',password:'abcde'});assert.equal(response.status,409);
response=await auth('login',{username:'NEWHERO',password:'wrong'});assert.equal(response.status,401);
response=await auth('login',{username:'NEWHERO',password:'12345'});assert.equal(response.status,200,'five-character password works for returning login');
const ids=['loginChoice','loginForm','loginSwitch','loginNote','loginTitle','loginSubmit','loginUsername','loginPassword','loginError','loginScreen','loading'],els=Object.fromEntries(ids.map(id=>[id,{value:'',disabled:false,focus(){},close(){this.open=false;},showModal(){this.open=true;}}]));
const calls=[],context={console,paused:0,resumed:0,realmPauseLoadingTimeout(){context.paused++;},realmStartLoadingTimeout(){context.resumed++;},$:id=>els[id],fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({account:url==='/api/auth/session'?null:{username:'NewHero'}})};}};vm.createContext(context);vm.runInContext(readFileSync(new URL('../dist/account-auth.js',import.meta.url),'utf8'),context);
const loginWait=vm.runInContext('ensureGameLogin()',context);await new Promise(resolve=>setImmediate(resolve));assert.equal(context.paused,1,'account choice pauses the game loading timeout');assert.equal(els.loginScreen.open,true);
vm.runInContext('renderLogin()',context);assert.equal(els.loginChoice.hidden,false);assert.equal(els.loginForm.hidden,true,'first screen contains choices, not the login form');
vm.runInContext("chooseLoginMode('register')",context);assert.equal(els.loginForm.hidden,false);assert.equal(els.loginChoice.hidden,true);assert.equal(els.loginSubmit.textContent,'Create account');assert.equal(els.loginPassword.minLength,5);
els.loginUsername.value='NewHero';els.loginPassword.value='12345';context.event={preventDefault(){}};await vm.runInContext('submitGameLogin(event)',context);await loginWait;assert.equal(calls.at(-1).url,'/api/auth/register');
vm.runInContext("chooseLoginMode('choose');chooseLoginMode('login')",context);assert.equal(els.loginSubmit.textContent,'Log in');els.loginPassword.value='12345';await vm.runInContext('submitGameLogin(event)',context);assert.equal(calls.at(-1).url,'/api/auth/login');
assert.equal(context.resumed,2,'successful account entry restarts the game loading timeout');
const html=readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.match(html,/id="chooseCreateAccount"/);assert.match(html,/id="chooseLogin"/);assert.match(html,/id="loginForm" hidden/);assert(!/minlength="12"/.test(html));
console.log('PASS: initial account choices, separate forms and endpoints, five-character passwords, duplicate/wrong-password handling, password hashing and persistent sessions.');
database.close();
