import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import fs from 'node:fs';import {handleSave,handlePlayers,handleAuth,SAVE_RESET_VERSION} from '../worker/api.js';
const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const env={DB:{prepare(sql){return{bind(...args){return{async first(){return db.prepare(sql).get(...args)},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return{meta:{changes:db.prepare(sql).run(...args).changes}}}}}}}}};
const req=(path,method='GET',cookie='',body)=>new Request('https://game.test'+path,{method,headers:{cookie,origin:'https://game.test'},...(body?{body:JSON.stringify({...body,resetVersion:SAVE_RESET_VERSION})}:{})});
async function guest(name){const r=await handleAuth(req('/api/auth/register','POST','',{username:name.replaceAll(' ','_'),password:'test-only-password-572!'}),env);assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0];assert.match(r.headers.get('set-cookie'),/HttpOnly/);const state={x:14,y:17,hp:30,gold:0,xp:{Combat:0},bag:{fish:1},character:{name,look:0},equipment:{weapon:'bronzeSword'}};assert.equal((await handleSave(req('/api/character','PUT',cookie,{state,revision:0}),env)).status,200);return cookie;}
const a=await guest('Player A'),b=await guest('Player B');assert.notEqual(a,b);
const presence=(cookie,scene='overworld',x=14)=>handlePlayers(req('/api/players','POST',cookie,{scene,x,y:17,heading:0,emote:'Hello!'}),env);
let r=await presence(a);assert.equal(r.status,200);assert.equal((await r.json()).players.length,0);r=await presence(b);let peers=(await r.json()).players;assert.equal(peers.length,1);assert.equal(peers[0].name,'Player A');assert.equal(peers[0].emote,'Hello!');assert(!JSON.stringify(peers).includes(a.split('=')[1]));
await presence(a,'overworld',16);peers=(await (await presence(b)).json()).players;assert.equal(peers[0].x,16);
assert.equal((await handlePlayers(req('/api/players','POST','',{scene:'overworld',x:14,y:17}),env)).status,401);
assert.equal((await presence(a,'overworld',1152)).status,400);
assert.equal((await presence(a,'overworld',1100)).status,200);
for(const [scene,x,y]of [['realm_aelindor_25',12,10],['realm_ironhollow_5',22,18],['realm_deepforge_0',8,10],['realm_crownreach_25',12,18]])assert.equal((await handlePlayers(req('/api/players','POST',a,{scene,x,y}),env)).status,200,scene);
for(const scene of ['realm_aelindor_26','realm_unknown_0','realm_crownreach_999','__proto__'])assert.equal((await handlePlayers(req('/api/players','POST',a,{scene,x:5,y:5}),env)).status,400,scene);
const saved=await (await handleSave(req('/api/character','GET',b),env)).json();assert.equal(saved.state.character.name,'Player B');
const kit={head:'iron_head',body:'bronze_body',shoulders:'gold_shoulders',hands:'mithril_hands',legs:'iron_legs',feet:'bronze_feet',weapon:'dragonslayer_weapon',shield:'iron_shield',crest:'helmet_crest_1',neck:'copperNecklace'};
saved.state.equipment=kit;saved.state.toolBelt={axe:true,pickaxe:true,tinderbox:true};
assert.equal((await handleSave(req('/api/character','PUT',b,{state:saved.state,revision:saved.revision}),env)).status,200);
await presence(b);peers=(await (await presence(a)).json()).players;assert.deepEqual(peers.find(p=>p.name==='Player B').equipment,kit,'second player sees every equipment slot');
const persisted=await (await handleSave(req('/api/character','GET',b),env)).json();assert.deepEqual(persisted.state.toolBelt,saved.state.toolBelt);
const spoof=await handlePlayers(req('/api/players','POST',b,{scene:'overworld',x:14,y:17,equipment:{body:'malicious-model'}}),env);assert.equal(spoof.status,200);peers=(await (await presence(a)).json()).players;assert.deepEqual(peers.find(p=>p.name==='Player B').equipment,kit,'presence body cannot override saved equipment');
db.exec('UPDATE player_presence SET seen_at=0');assert.equal((await (await presence(b)).json()).players.length,0);
console.log('PASS: two separate username accounts, durable saves, real player discovery, movement/emote synchronization, session secrecy, stale-player expiry and rejected invalid writes.');
