import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const root=new URL('../',import.meta.url),wasm=fs.readFileSync(new URL('dist/native/veldren-core.wasm',root));
const listeners={};
const window={addEventListener(type,listener){listeners[type]=listener;}};
const context={window,fetch:async url=>({ok:true,status:200,arrayBuffer:async()=>wasm.buffer.slice(wasm.byteOffset,wasm.byteOffset+wasm.byteLength)}),realmAssetURL:path=>'/'+path,veldrenAnimationInput:()=>({clip:5,flags:2,idlePhase:.2,phase:.4,blend:.8}),WebAssembly,DataView,Number,Error,Set,WeakMap};
vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('dist/native-runtime.js',root),'utf8'),context,{filename:'native-runtime.js'});
const native=await window.realmNativeReady;
assert.equal(native.kind,'cpp-wasm');assert.equal(native.abi,11);
const villager={type:'villager',x:10,y:0,drawX:0,drawY:0},wolf={kind:'wolf',x:110,y:0,drawX:100,drawY:0};
native.stepActors([villager,wolf],.5,0,0,null,1);
assert(Math.abs(villager.drawX-.375)<.0001,'C++ applies the villager walk speed');
assert(Math.abs(wolf.drawX-100.8)<.0001,'C++ applies the wolf walk speed');
assert(villager._creatureMotion.phase>0&&villager._creatureMotion.blend>0&&villager._creatureMotion.speed>0,'C++ returns batched gait state');
native.animateActors([villager,wolf],.5);assert.equal(villager._nativeAnimation.clip,'attack');assert.equal(villager._nativeAnimation.baseClip,'walk');assert(Math.abs(villager._nativeAnimation.phase-.4)<.0001);
const crowd=Array.from({length:129},(_,i)=>({kind:'goblin',x:110+i,y:0,drawX:100+i,drawY:0})),selected=crowd[0];
native.stepActors(crowd,.1,0,0,selected,2);
assert(Math.abs(selected.drawX-100.125)<.0001,'selected distant actors stay responsive');
assert.equal(crowd[1].drawX,101,'ordinary distant actors wait for the native budget interval');
native.stepActors(crowd,.15,0,0,selected,2.15);
assert(Math.abs(crowd[1].drawX-101.3125)<.0001,'native core applies the accumulated distant-actor step');
assert.equal(native.rules.skillLevel('Attack',83),2);assert.equal(native.rules.skillThreshold('Attack',2),83);
assert.equal(native.rules.skillLevel('Worship',140),3);assert.equal(native.rules.combatLevel({Hitpoints:10,Attack:1,Strength:1,Defense:1,Worship:1,Magic:1,Ranged:1}),3);
assert(Math.abs(native.rules.attackRollChance(100,50)-(1-52/202))<.0001);
assert.equal(native.rules.physicalMaxHit(20,64,1),4);assert.equal(native.rules.magicMaxHit(10,25),12);
assert(Math.abs(native.rules.gatheringChance(20,15,2,.1)-.595)<.0001);assert(Math.abs(native.rules.firemakingChance(20,15)-.51)<.0001);
assert(Math.abs(native.rules.cookingBurnChance(15,1,34)-.1842424)<.0001);assert(Math.abs(native.rules.ironSmeltChance(20)-.55)<.0001);
assert.equal(JSON.stringify(native.rules.combatRewards(3,'melee','balanced')),JSON.stringify({Hitpoints:12,Attack:12,Strength:12,Defense:12}));
const cells=new Uint8Array(12*12);for(let y=1;y<11;y++)if(y!==6)cells[y*12+5]=1;
const route=native.pathfind(cells,12,12,2,2,9,9,false,0,144,[]);
assert(route.length>0);assert.equal(route.at(-1)[0],9);assert.equal(route.at(-1)[1],9);assert(route.some(([x,y])=>x===5&&y===6));
assert.equal(native.transactions.inventoryEntrySlots(20,true),1);assert.equal(native.transactions.inventoryEntrySlots(3,false,1),2);
assert.equal(native.transactions.transferCount(10,7,4),4);assert.equal(JSON.stringify(native.transactions.spendCoins(5,20,12)),JSON.stringify({loose:0,pouch:13}));
assert.equal(native.transactions.spendCoins(5,2,12),null);assert.equal(native.transactions.craftFits(25,2,false,false,2,25),true);
assert.equal(native.stateMachines.actionEvents(1,.95,1.8,false),1);assert.equal(native.stateMachines.actionEvents(2,.95,1.8,false),3);
const move=native.stateMachines.enemyCombatTick(.02,2,0,false,false,.29,2.3);assert.equal(move.events,1);assert(Math.abs(move.enemyClock)<.001);
const attack=native.stateMachines.enemyCombatTick(.1,1,0,false,true,move.enemyClock,move.retaliationClock);assert.equal(attack.events,2);assert(Math.abs(attack.retaliationClock)<.001);
assert.equal(native.stateMachines.requirementsMet([[5,5],[4,4],[3,3]]),true);assert.equal(native.stateMachines.requirementsMet([[5,5],[3,4]]),false);
assert.equal(native.stateMachines.worldTimerEvents(1000,999,0,NaN,0),1);assert.equal(native.stateMachines.worldTimerEvents(1000,NaN,9,999,5),2);
listeners.pagehide();assert.throws(()=>native.stepActors([],0.1,0,0,null,3),/stopped/);
console.log('PASS: browser bridge loads the C++ WASM core and delegates actor simulation');
