import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {syncSharedWorld} from '../worker/shared-world.js';
import catalog from '../worker/shared-catalog.json' with {type:'json'};
const sql=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const db={prepare(query){return {bind(...args){return {query,args,async first(){return sql.prepare(query).get(...args)},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return {meta:{changes:sql.prepare(query).run(...args).changes}}}}}}},async batch(rows){sql.exec('BEGIN');try{const out=rows.map(({query,args})=>({meta:{changes:sql.prepare(query).run(...args).changes}}));sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};
let now=Date.now(),seq=0;const realNow=Date.now,realRandom=Math.random;Date.now=()=>now;Math.random=()=>0;
const env={DB:db},state={xp:{Woodcutting:0,Magic:10000,'Relic Shaping':0},bag:{},equipment:{}};
const tree=Object.values(catalog.entities).find(e=>e.scene==='overworld'&&e.type==='tree'&&e.resource.resourceId==='normal');
const packet=(events=[],watch=[tree.id],key)=>({scene:tree.scene,x:tree.x+1,y:tree.y,world:{protocol:1,watch,events,treeKey:key}});
const event=(kind,more={})=>({id:'p2-'+(++seq),kind,scene:tree.scene,entity:tree.id,generation:1,...more});
const initial=await syncSharedWorld(env,'a',state,packet(),now,'p2');assert(initial.treeView);
const unchanged=await syncSharedWorld(env,'a',state,packet([],[],initial.treeView.key),now,'p2');assert.equal(unchanged.treeView,null);
const ea=event('harvest'),eb=event('harvest');const race=await Promise.all([syncSharedWorld(env,'a',state,packet([ea]),now,'p2'),syncSharedWorld(env,'b',state,packet([eb]),now,'p2')]);
assert.equal(race.flatMap(w=>w.receipts).filter(r=>[ea.id,eb.id].includes(r.id)&&r.ok&&!r.missed).length,1);
let late=await syncSharedWorld(env,'late',state,packet([],[]),now,'p2');const stump=late.treeView.states.find(r=>r[0]===tree.id);assert(stump&&stump[2]>now);assert(stump[3]>now&&stump[3]<stump[2]);
const duplicate=await syncSharedWorld(env,'a',state,packet([ea]),now,'p2');assert.equal(duplicate.receipts.filter(r=>r.id===ea.id).length,1);
now=stump[2]+1;late=await syncSharedWorld(env,'newcomer',state,packet([],[]),now,'p2');const regrown=late.treeView.states.find(r=>r[0]===tree.id);assert.equal(regrown[2],0);assert.equal(regrown[1],2);
const next=event('harvest',{generation:2});const again=await syncSharedWorld(env,'a',state,packet([next]),now,'p2');assert(again.receipts.find(r=>r.id===next.id).ok);
const altar=catalog.relicAnchors.altar,craftState={...state,relicQuest:{stage:6},bag:{unfinished_air:1},xp:{'Relic Shaping':0}};
const craft=event('relic',{action:'charge',recipe:'air'}),at={scene:altar.scene,x:altar.x+1,y:altar.y,world:{protocol:1,watch:[],events:[craft]}};
now+=3000;const result=await syncSharedWorld(env,'crafter',craftState,at,now,'p2'),reward=result.receipts.find(r=>r.id===craft.id);assert(reward.ok);assert.equal(reward.give.airRunes,10);assert.equal(reward.give.coins,150);assert.equal(reward.stage,7);
const retry=await syncSharedWorld(env,'crafter',craftState,at,now,'p2');assert.deepEqual(retry.receipts.find(r=>r.id===craft.id),reward);
now+=3000;const invalid=event('relic',{action:'charge',recipe:'air'});const far=await syncSharedWorld(env,'far',craftState,{...at,x:altar.x+20,world:{...at.world,events:[invalid]}},now,'p2');assert(!far.receipts.find(r=>r.id===invalid.id).ok);
const locked=await syncSharedWorld(env,'locked',{...craftState,relicQuest:{stage:0}},at,now,'p2');assert(!locked.receipts.find(r=>r.id===craft.id).ok);
now+=3000;const replay=event('relic',{action:'charge',recipe:'air'});const stale=await syncSharedWorld(env,'crafter',craftState,{...at,world:{...at.world,events:[replay]}},now,'p2');assert(!stale.receipts.find(r=>r.id===replay.id).ok);
const cross=catalog.relicAnchors.crossing,back=catalog.relicAnchors.return;
async function crossing(actor,stage,position,destination){const ev=event('teleport',{mode:'relic',destination,scene:position.scene});const w=await syncSharedWorld(env,actor,{...state,tutorialReward:true,relicQuest:{stage}},{...position,world:{protocol:1,events:[ev]}},now,'p2');return w.receipts.find(r=>r.id===ev.id);}
const permit=await crossing('lake-traveller',4,cross,'fairy_between');assert(permit.ok);assert.deepEqual(permit.entry,[20,49]);assert.equal(permit.color,'green');
assert(!(await crossing('locked-lake',3,cross,'fairy_between')).ok);assert(!(await crossing('remote-lake',4,{...cross,x:cross.x+20},'fairy_between')).ok);assert(!(await crossing('wrong-way',4,cross,'lair_veyr')).ok);assert((await crossing('return-traveller',5,back,'overworld')).ok);
Date.now=realNow;Math.random=realRandom;
console.log('PASS: competing cutters, stump/regrowth/late arrival, tree generations, omitted unchanged snapshots, receipt retries, one-time quest rewards, altar proximity/unlock, and server-approved Fairy crossings.');
