const assert=require('node:assert/strict');
const {ctx,vm,fs}=require('../scripts/game-fixture.cjs');
ctx.console={log:console.log.bind(console),warn:()=>{}};
vm.runInContext(fs.readFileSync(__dirname+'/../dist/terrain-editor-runtime.js','utf8'),ctx,{filename:'terrain-editor-runtime.js'});
const evalInGame=source=>vm.runInContext(source,ctx);
evalInGame(`
 const terrain=window.VeldrenTerrainEdits;
 assert.equal(terrain.count.heightNodes,0);
 const before=landHeight(120,120),road=realmTerrainMaterial([1,0,0],120,120);
 assert.equal(road,5);
 const far={buffer:{id:'far'},x:204,z:204,key:'8:2:200:200'},near={buffer:{id:'near'},x:124,z:124,key:'8:2:120:120'},released=[];
 realmGPU={terrain:new Map([['overworld',new Map([[near.key,near],[far.key,far]])]]),gl:{deleteBuffer(buffer){released.push(buffer.id)}}};
 realmNavigation.set('overworld',{cells:new Uint8Array(1)});
 terrain.beginStroke();
 const a=terrain.stroke({mode:'raise',scene:'overworld',x:120,z:120,radius:1.5,strength:.8});
 assert(a.changed>0);assert(landHeight(120,120)>before+.7,'the actual world heightfield changes');
 assert.equal(realmNavigation.has('overworld'),false,'brush invalidates cached pathfinding slopes');
 assert.deepEqual(released,['near'],'only nearby GPU terrain chunks were released');
 assert(realmGPU.terrain.get('overworld').has(far.key));
 terrain.stroke({mode:'paint',scene:'overworld',x:120.5,z:120.5,radius:1,strength:1,material:'grass'});
 assert.equal(terrain.paint(120,120),'grass');
 assert.equal(realmTerrainMaterial([1,0,0],120,120),1,'manual grass overrides a procedural road surface');
 const commit=terrain.endStroke();assert(commit.changed);assert.equal(commit.undo,1,'one history entry covers sculpt and paint drag');
 const stored=terrain.serialize();assert(stored.scenes.overworld.heightNodes.some(p=>p.x===120&&p.z===120));
 const raised=landHeight(120,120);
 assert(terrain.undo().changed);assert(Math.abs(landHeight(120,120)-before)<.001);assert.equal(terrain.paint(120,120),null);
 assert(terrain.redo().changed);assert(Math.abs(landHeight(120,120)-raised)<.001);assert.equal(terrain.paint(120,120),'grass');
 assert(terrain.applyDocument(stored).unchanged,'same saved layer keeps local undo stack');assert.equal(terrain.history.undo,1);
 assert.equal(terrain.applyDocument({version:1,scenes:{overworld:{heightNodes:[{x:120,z:120,delta:Infinity}],paintCells:[]}}}).applied,false);
 assert.equal(terrain.paint(120,120),'grass','malformed saved terrain is quarantined');
 terrain.beginStroke();terrain.stroke({mode:'flatten',x:120,z:120,radius:1.5,strength:1,target:before});terrain.endStroke();
 assert(Math.abs(landHeight(120,120)-before)<.001,'flatten uses fixed drag target');
 terrain.beginStroke();terrain.stroke({mode:'raise',x:120,z:120,radius:1.5,strength:1});terrain.endStroke();
 const peak=landHeight(120,120);terrain.beginStroke();terrain.stroke({mode:'smooth',x:120,z:120,radius:1.5,strength:1});terrain.endStroke();
 assert(landHeight(120,120)<peak,'smooth averages neighbor heights');
 terrain.beginStroke();terrain.stroke({mode:'lower',x:120,z:120,radius:1.5,strength:.25});terrain.endStroke();
 assert(landHeight(120,120)<peak,'lower reduces height');
 const river=terrain.stroke({mode:'raise',x:37,z:30,radius:.5,strength:.5});terrain.endStroke();
 assert.equal(terrain.heightDelta(37,30),0,'submerged river nodes retain their authored waterbed');
 assert(terrain.reset().changed);assert.equal(terrain.count.heightNodes,0);assert.equal(terrain.count.paintCells,0);
 assert(terrain.undo().changed,'reset is undoable');assert(terrain.count.heightNodes>0);
 terrain.applyDocument(stored);assert(Math.abs(landHeight(120,120)-raised)<.001,'saved terrain reloads into live world height');
 assert(!terrainCellBlocked(126,126));terrain.beginStroke();terrain.stroke({mode:'raise',x:126,z:126,radius:.5,strength:2});terrain.endStroke();
 assert(terrainCellBlocked(126,126),'steep sculpted cells become impassable for game pathfinding');
 terrain.undo();assert(!terrainCellBlocked(126,126),'undo restores a walkable slope');
 console.log('PASS: live height and pathfinding slope, material override, selective GPU/nav invalidation, undo/redo/flatten/smooth/reset, safe reload.');
`);
