import { sqliteTable,text,integer,index } from 'drizzle-orm/sqlite-core';
export const characterSaves=sqliteTable('character_saves',{userId:text('user_id').primaryKey(),state:text('state').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull()});

export const playerPresence=sqliteTable('player_presence',{playerId:text('player_id').primaryKey(),scene:text('scene').notNull(),payload:text('payload').notNull(),seenAt:integer('seen_at').notNull()},table=>[index('idx_presence_scene_seen').on(table.scene,table.seenAt)]);
export const gameAccounts=sqliteTable('game_accounts',{id:text('id').primaryKey(),username:text('username').notNull(),normalizedUsername:text('normalized_username').notNull().unique(),passwordHash:text('password_hash').notNull(),createdAt:integer('created_at').notNull()});
export const gameSessions=sqliteTable('game_sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull().references(()=>gameAccounts.id),expiresAt:integer('expires_at').notNull()});
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),window:integer('window').notNull(),attempts:integer('attempts').notNull()});
export const globalResets=sqliteTable('global_resets',{id:text('id').primaryKey(),reason:text('reason').notNull(),characterCount:integer('character_count').notNull(),sessionCount:integer('session_count').notNull(),presenceCount:integer('presence_count').notNull(),resetAt:text('reset_at').notNull(),completed:integer('completed').notNull().default(0)});
export const gameMaintenance=sqliteTable('game_maintenance',{id:integer('id').primaryKey(),runId:text('run_id').notNull(),status:text('status').notNull(),kickAt:integer('kick_at').notNull()});
export const socialMessages=sqliteTable('social_messages',{id:integer('id').primaryKey({autoIncrement:true}),author:text('author').notNull(),recipient:text('recipient'),scene:text('scene').notNull(),x:integer('x').notNull(),y:integer('y').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_messages_time').on(t.createdAt),index('idx_messages_recipient').on(t.recipient,t.id)]);
export const friendships=sqliteTable('friendships',{pair:text('pair').primaryKey(),a:text('a').notNull(),b:text('b').notNull(),requester:text('requester').notNull(),status:text('status').notNull()});
export const playerTrades=sqliteTable('player_trades',{id:text('id').primaryKey(),a:text('a').notNull(),b:text('b').notNull(),status:text('status').notNull(),revision:integer('revision').notNull(),payload:text('payload').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_trade_a').on(t.a,t.status),index('idx_trade_b').on(t.b,t.status)]);
