import { sqliteTable,text,integer,index,primaryKey } from 'drizzle-orm/sqlite-core';
export const characterSaves=sqliteTable('character_saves',{userId:text('user_id').primaryKey(),state:text('state').notNull(),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull()});

export const playerPresence=sqliteTable('player_presence',{playerId:text('player_id').primaryKey(),scene:text('scene').notNull(),payload:text('payload').notNull(),seenAt:integer('seen_at').notNull()},table=>[index('idx_presence_scene_seen').on(table.scene,table.seenAt),index('idx_presence_seen').on(table.seenAt)]);
export const gameAccounts=sqliteTable('game_accounts',{id:text('id').primaryKey(),username:text('username').notNull(),normalizedUsername:text('normalized_username').notNull().unique(),passwordHash:text('password_hash').notNull(),createdAt:integer('created_at').notNull()});
export const gameSessions=sqliteTable('game_sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull().references(()=>gameAccounts.id),expiresAt:integer('expires_at').notNull()});
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),window:integer('window').notNull(),attempts:integer('attempts').notNull()});
export const globalResets=sqliteTable('global_resets',{id:text('id').primaryKey(),reason:text('reason').notNull(),characterCount:integer('character_count').notNull(),sessionCount:integer('session_count').notNull(),presenceCount:integer('presence_count').notNull(),resetAt:text('reset_at').notNull(),completed:integer('completed').notNull().default(0)});
export const gameMaintenance=sqliteTable('game_maintenance',{id:integer('id').primaryKey(),runId:text('run_id').notNull(),status:text('status').notNull(),kickAt:integer('kick_at').notNull()});
export const socialMessages=sqliteTable('social_messages',{id:integer('id').primaryKey({autoIncrement:true}),author:text('author').notNull(),recipient:text('recipient'),audience:text('audience').notNull().default('[]'),scene:text('scene').notNull(),x:integer('x').notNull(),y:integer('y').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_messages_time').on(t.createdAt),index('idx_messages_recipient').on(t.recipient,t.id)]);
export const friendships=sqliteTable('friendships',{pair:text('pair').primaryKey(),a:text('a').notNull(),b:text('b').notNull(),requester:text('requester').notNull(),status:text('status').notNull()});
export const playerTrades=sqliteTable('player_trades',{id:text('id').primaryKey(),a:text('a').notNull(),b:text('b').notNull(),status:text('status').notNull(),revision:integer('revision').notNull(),payload:text('payload').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('idx_trade_a').on(t.a,t.status),index('idx_trade_b').on(t.b,t.status)]);

export const socialSettings=sqliteTable('social_settings',{accountId:text('account_id').primaryKey(),publicMode:text('public_mode').notNull().default('on'),privateMode:text('private_mode').notNull().default('on'),tradeMode:text('trade_mode').notNull().default('on')});
export const ignoredPlayers=sqliteTable('ignored_players',{owner:text('owner').notNull(),target:text('target').notNull()},t=>[index('idx_ignored_owner').on(t.owner,t.target)]);

export const betaCheckpoints=sqliteTable('beta_checkpoints',{id:text('id').primaryKey().references(()=>globalResets.id),restoreFrom:text('restore_from')});
export const archivedCharacters=sqliteTable('archived_characters',{checkpointId:text('checkpoint_id').notNull().references(()=>betaCheckpoints.id),userId:text('user_id').notNull(),state:text('state').notNull(),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.checkpointId,t.userId]})]);
export const sharedEntities=sqliteTable('shared_entities',{id:text('id').primaryKey(),scope:text('scope').notNull(),scene:text('scene').notNull(),entityId:text('entity_id').notNull(),state:text('state').notNull(),revision:integer('revision').notNull().default(0)},t=>[index('idx_shared_entity_scene').on(t.scope,t.scene)]);
export const sharedEvents=sqliteTable('shared_events',{id:text('id').primaryKey(),scope:text('scope').notNull(),scene:text('scene').notNull(),actor:text('actor').notNull(),kind:text('kind').notNull(),result:text('result').notNull(),createdAt:integer('created_at').notNull(),acked:integer('acked').notNull().default(0)},t=>[index('idx_shared_actor_receipts').on(t.actor,t.acked,t.createdAt),index('idx_shared_events_scene').on(t.scope,t.scene,t.createdAt),index('idx_shared_event_cleanup').on(t.acked,t.createdAt),index('idx_shared_effect_cleanup').on(t.kind,t.acked,t.createdAt)]);
export const sharedObjects=sqliteTable('shared_objects',{id:text('id').primaryKey(),scope:text('scope').notNull(),scene:text('scene').notNull(),kind:text('kind').notNull(),payload:text('payload').notNull(),expiresAt:integer('expires_at').notNull(),revision:integer('revision').notNull().default(0)},t=>[index('idx_shared_objects_scene').on(t.scope,t.scene,t.expiresAt),index('idx_shared_object_cleanup').on(t.expiresAt)]);
export const sharedClocks=sqliteTable('shared_clocks',{id:text('id').primaryKey(),readyAt:integer('ready_at').notNull(),nonce:text('nonce').notNull()});

export const editorWorld=sqliteTable('editor_world',{id:integer('id').primaryKey(),revision:integer('revision').notNull(),document:text('document').notNull(),previousDocument:text('previous_document'),updatedBy:text('updated_by').notNull()});
