import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import vm from 'node:vm';
import worker from '../../dist/server/index.js';
const db=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const env={DB:{prepare(sql){return{args:[],bind(...args){this.args=args;return this},async first(){return db.prepare(sql).get(...this.args)},async run(){return db.prepare(sql).run(...this.args)}}},async batch(statements){db.exec('BEGIN');try{for(const statement of statements)await statement.run();db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}}}};
const call=async(method='GET',bindings=env)=>worker.fetch(new Request('https://veldren.test/api/status',{method}),bindings);
let response=await call();assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');assert.equal((await response.json()).players,0,'empty game is online');
const now=Date.now();const add=(id,scene,seen)=>db.prepare('INSERT INTO player_presence VALUES (?,?,?,?)').run(id,scene,JSON.stringify({name:'Private name',x:10,y:10}),seen);
add('a','tutorial',now);add('b','overworld',now);add('stale','overworld',now-15000);
let data=await (await call()).json();assert.equal(data.players,2,'count across scenes excludes expired presence');assert.equal(data.status,'online');assert(!JSON.stringify(data).includes('Private name'));
db.prepare('UPDATE player_presence SET scene=? WHERE player_id=?').run('inn','b');assert.equal((await (await call()).json()).players,2,'scene change does not duplicate character');
assert(db.prepare('EXPLAIN QUERY PLAN SELECT COUNT(*) FROM player_presence WHERE seen_at > ?').all(now-12000).some(r=>r.detail.includes('idx_presence_seen')));
db.prepare('INSERT INTO game_maintenance VALUES (1,?,?,?)').run('status-test','countdown',now+120000);
data=await (await call()).json();assert.equal(data.status,'online');assert.equal(data.maintenanceAt,now+120000);assert.equal(data.players,2);
db.exec('UPDATE game_maintenance SET kick_at=0');response=await call();assert.equal(response.status,200,'status remains reachable during maintenance');data=await response.json();assert.equal(data.status,'maintenance');assert.equal(data.players,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM player_presence').get().n,0);
response=await call('GET',{});assert.equal(response.status,503);assert.equal((await response.json()).players,null,'database failure must not claim zero players');
assert.equal((await call('POST')).status,405);assert.equal(await (await call('HEAD')).text(),'');
const html = await (await worker.fetch(new Request('https://veldren.test/'), {})).text();
assert(html.includes('Veldren Beta v1'));
assert(html.includes('id="realm-status"'));
assert(html.includes('/api/status'));
// Exercise the actual homepage script as successive responses arrive.
const elements=Object.fromEntries(['realm-status','server-state','player-count','status-note'].map(id=>[id,{dataset:{},textContent:''}]));
let mode='online',next,listener;
const context={document:{hidden:false,getElementById:id=>elements[id],addEventListener:(_,fn)=>listener=fn},AbortController,setTimeout(fn,ms){if(ms===15000)next=fn;return 1},clearTimeout(){},fetch:async()=>{if(mode==='network')throw Error('Disconnected');return{ok:mode!=='offline',status:mode==='offline'?503:200,json:async()=>({status:mode,players:mode==='offline'?null:mode==='maintenance'?0:3})}}};
vm.runInNewContext(fs.readFileSync('client/landing-status.js','utf8'),context);await new Promise(setImmediate);
assert.equal(elements['server-state'].textContent,'Server online');assert.equal(elements['player-count'].textContent,'3 players in game');
for(const [value,label]of [['maintenance','Server maintenance'],['offline','Server offline'],['network','Server unreachable']]){mode=value;await next();assert.equal(elements['server-state'].textContent,label);if(value!=='maintenance')assert.equal(elements['player-count'].textContent,'Player count unavailable');}
context.document.hidden=true;listener();context.document.hidden=false;mode='online';listener();await new Promise(setImmediate);assert.equal(elements['server-state'].textContent,'Server online');
console.log('PASS: real cross-scene presence count, stale expiry, indexed lookup, public maintenance status, unavailable counts, HTTP methods, release page and polling recovery.');
