import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('../../',import.meta.url),events=[];
const context={console,TextEncoder,TextDecoder,DataView,WebAssembly,AbortController,URL,Map,Set,
 realmAssetURL:p=>p,VELDREN_CONTEXT:'editor',addEventListener(){},
 fetch:async path=>{const bytes=fs.readFileSync(new URL('client/'+String(path).replace(/^\//,''),root));return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),json:async()=>JSON.parse(bytes.toString())};}};
context.window=context;vm.createContext(context);
for(const path of ['client/asset-runtime.js','client/native-runtime.js','client/editor/commands.js'])vm.runInContext(fs.readFileSync(new URL(path,root),'utf8'),context);
const native=await context.realmNativeReady,n=native.scenes;
const entity=(id,parent=null)=>({id,name:id,parent,active:true,transform:{position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]},components:{},metadata:{}});

n.upsert('town',entity('house'));n.upsert('town',entity('wall','house'));n.upsert('town',entity('door','wall'));
const commands=context.createVeldrenEditorCommands(n,()=> 'town');
const run=(op)=>commands.execute(op.op,[op]),get=id=>n.entity('town',id),comp=(id,type)=>get(id).components[type];
run({op:'addComponent',id:'wall',component:'Light',fields:{type:'point',intensity:3,color:[1,1,1]}});
run({op:'addComponent',id:'house',component:'BuildingAccess',fields:{entrance:'door'}});
run({op:'transform',id:'house',transform:{position:[4,0,5],scale:[2,1,3]}});
const definition=run({op:'prefabCreate',id:'house',name:'Test house'}).created[0];
assert.throws(()=>run({op:'delete',id:definition}),/Unpack or delete/);
assert(comp(definition,'PrefabDefinition'));assert.equal(get(definition).active,false);
const instance=run({op:'prefabInstantiate',id:definition,transform:{position:[12,2,8]}}).created[0];
const wall=n.read('town').entities.find(e=>e.parent===instance).id;
const door=n.read('town').entities.find(e=>e.parent===wall).id;
assert.equal(comp(instance,'BuildingAccess').entrance,door,'internal entity links remap');
assert.equal(get(instance).transform.position[0],12);assert.deepEqual(Array.from(get(instance).transform.scale),[2,1,3],'prefab preserves authored root scale');
run({op:'field',id:wall,component:'Light',field:'intensity',value:9});
run({op:'field',id:'wall',component:'Light',field:'color',value:[.2,.3,.4]});
run({op:'prefabUpdate',id:'house'});
assert.equal(comp(wall,'Light').intensity,9,'local override remains');
assert.deepEqual(Array.from(comp(wall,'Light').color),[.2,.3,.4],'inherited field updates');
assert.equal(get(instance).transform.position[0],12,'instance placement remains');
commands.undo();assert.deepEqual(Array.from(comp(wall,'Light').color),[1,1,1]);commands.redo();
run({op:'create',entity:{...entity('new-part','house'),components:{Collider:{size:[1,2,3]}}}});
run({op:'prefabUpdate',id:'house'});
const added=n.read('town').entities.find(e=>e.parent===instance&&e.components.Collider);assert(added,'new template child propagates');
run({op:'delete',id:door});run({op:'prefabUpdate',id:'house'});assert.equal(get(door),null,'local deletion remains');
run({op:'prefabRevert',id:instance});assert.equal(comp(wall,'Light').intensity,3);assert.equal(get(instance).transform.position[0],12);
assert(n.read('town').entities.some(e=>e.parent===wall),'revert restores deleted inherited child');
run({op:'create',entity:{...entity('nested-new','new-part')}});run({op:'prefabUpdate',id:'house'});
run({op:'delete',id:'new-part'});run({op:'prefabUpdate',id:'house'});assert.equal(get(added.id),null,'unchanged removed leaf disappears');
const document=JSON.stringify(n.serialize());n.load(JSON.parse(document));assert.equal(JSON.stringify(n.serialize()),document,'prefabs persist in canonical Scene document');
run({op:'prefabUnpack',id:instance});assert.equal(comp(instance,'PrefabInstance'),undefined);commands.undo();assert(comp(instance,'PrefabInstance'));
console.log('PASS: actual-WASM prefab create/instantiate, internal links, overrides, update undo/redo, add/delete, revert, unpack and exact serialization');
native.destroy();
